### ISSUE TITLE
Fail gracefully if PURL is absent

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/item-release#55]
Occasionally, a stakeholder or operator will release an object that does not have a PURL (objects set to dark, for instance, or failing to filter registered-only objects out of a release list). Currently, update-marc fails with an error of "404 Not Found" if the PURL is missing - we should consider a more graceful approach to failure (that includes being able to skip the step if necessary).

**Comment by peetucket** [comment]
I'm not sure this is still a thing... I have done some tests on a dark object locally and I do not see anything throwing an error (either the update marc logic or the robot itself).

The update marc step does indeed attempt a PURL  call (though it will now being doing it in new web service call to dor-services-app instead of directly in the item-release robot suite).  But this web service call will still succeed with a 201 even if the PURL doesn't exist.   The update marc step basically fetches the object from Fedora to do its logic, and as far as I can tell, the call to PURL comes from dor-services gem when checking release tags, and then only as an extra check.  It is not required for success.
