### ISSUE TITLE
Need to implement the indication of "what=self" for collection in the release tag attribute

### ISSUE THREAD

**Issue by lmcglohon** [sul-dlss/item-release#63]
The "what" release tag attribute should be used to indicate if a collection should be released along with all its members (when what="collection") or when the collection should be released without all its members (when what="self").

The release of a collection description on its own would be unusual though supported.  The use case that what="self" for a collection supports is when one is releasing only selected members of a collection and need the collection description to appear in Seachworks as well -- the reverse of releasing a collection as a whole.

**Comment by LynnMcRae** [comment]
The fix is needed in releaseWF, first step, to not spawn releaseWF for each of the members.  Turns out running the release WF for members does no harm because the dor-services  item-level evaluation for release apparently does factor in what=collection|self in the collection, so this is mainly an optimization to avoid republishing large quantities of collection members for no purpose.

**Comment by blalbrit** [comment]
Specifically - at the release-members step, we should skip that step if what="self"
